# Generated by Django 5.2.4 on 2025-07-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wired',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('URL', models.URLField()),
                ('date_of_publish', models.DateField()),
                ('picture', models.ImageField(default='images/default.jpeg', upload_to='images/')),
            ],
            options={
                'verbose_name': 'Wired',
                'verbose_name_plural': 'Wired',
            },
        ),
    ]
