# Generated by Django 5.2.4 on 2025-07-11 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wired',
            options={'ordering': ['-date_of_publish'], 'verbose_name': 'Wired', 'verbose_name_plural': 'Wired'},
        ),
        migrations.AlterField(
            model_name='wired',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
